name: CI/CD for Static Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node (for optional JS tools)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install HTMLHint (optional)
        run: npm install -g htmlhint

      - name: Lint HTML (optional)
        run: htmlhint index.html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
